### PR TITLE
Added optional delay between request and response

### PR DESCRIPTION
**Pull request by parthkalgaonkar**
- This is intended to allow master enough time to switch dePin to 0

### CODE REVIEW

**Comment by CMB27** [comment]
I have not experienced an issue with this. Below is a screenshot of the timings I usually get.

ModbusAnalysisScreenshot

Can you give me more information on your setup: devices used, baud rate, and anything else that may be relevant.
Thanks,

**Comment by parthkalgaonkar** [comment]
Here's my setup

- Arduino UNO as the modbus slave.
- Raspberry Pi Zero using (a rust wrapper for) libmodbus as the master
- 9600 baud rate

**Comment by CMB27** [comment]
My impression is that the problem is on the Raspberry Pi Zero side. It sounds like it doesn't have very tight timing control of the DE pin of the RS-485 transceiver.

**Comment by parthkalgaonkar** [comment]
Yes that is accurate. RTS pin toggle has to be done via ioctl calls from user space. This adds a ton of latency

**Comment by CMB27** [comment]
Sorry for the delayed response.
I am okay with the feature add, but I do want a few changes before merging.
- Change `_respDelay` to `_responseDelay`.
- Change the `_responseDelay` type to `unsigned long`. (Timing values are always `unsigned long`.)
- Change the name of the set function from `configureRespDelay` to `setResponseDelay`.
- Set the initial value of `_responseDelay` to `0` in its declaration in the header (.h) file, rather than in each of the constructors.

**Comment by CMB27** [comment]
I would also like an updated README with a section describing the `setResponseDelay` function.

**Review by CMB27 — APPROVED** [review]

**Pull request merged**
